name: Check JSON-LD and JSON files are valid

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths:
      - '**/jsonld-contexts/**'
      - '**/ngsild-payloads/**'

jobs:
  check-context-valid-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install jq
        run: |
          sudo apt update && sudo apt install jq
      - name: Check JSON-LD files
        run: |
          for file in $(find . -name "*.jsonld"); do
            printf "Checking $file .. "
            jq empty $file && echo "OK"
          done || exit 1
      - name: Check JSON files
        run: |
          for file in $(find . -name "*.json"); do
            printf "Checking $file .. "
            jq empty $file && echo "OK"
          done || exit 1
        shell: bash